name: Auto-Generate Requirements Documentation

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'Others/docs/**'
      - 'PinYin_Requirements_Specification.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Generate requirements documentation
      run: |
        python Others/generate_requirements_doc.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Others/docs/
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update requirements documentation

        - Updated requirements specification based on current codebase
        - Regenerated auto-generated documentation
        - Updated localization data

        Generated on: $(date)"
        git push 