name: Generate Requirements Documentation (GitHub App)

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - 'PinYin_Requirements_Specification.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Generate requirements documentation
      run: |
        python generate_requirements_doc.py
        
    - name: Create Pull Request with changes
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Auto-update requirements documentation"
        title: "Auto-update requirements documentation"
        body: |
          This PR was automatically generated to update the requirements documentation.
          
          Changes include:
          - Updated requirements specification based on current codebase
          - Regenerated auto-generated documentation
          - Updated localization data
          
          Generated on: ${{ github.event.head_commit.timestamp }}
        branch: auto-update-requirements-${{ github.run_number }}
        delete-branch: true
        path: docs/
        committer: GitHub <noreply@github.com>
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> 