name: Generate Requirements Documentation

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Generate requirements documentation
      run: |
        python generate_requirements_doc.py
        
    - name: Upload generated documentation as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: requirements-documentation
        path: docs/
        retention-days: 30 